language: r
r:
  - oldrel
  - release
  - devel

sudo: required

before_install:
  - cd pkg

warnings_are_errors: true

cache: packages

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
