branches:
  only:
  - master

env:
  global:
  - RGL_USE_NULL=TRUE

language: r
sudo: required
cache: packages

warnings_are_errors: true
r_build_args: '--no-manual'
r_check_args: '--no-build-vignettes --no-manual'

r:
  - bioc-release
  - bioc-devel

before_install:
  - Rscript -e 'update.packages(ask = FALSE)'
  - Rscript -e "source('https://bioconductor.org/biocLite.R'); biocLite()"

r_packages:
  - devtools
  - covr
  - BiocManager

r_github_packages:
  - r-lib/devtools
  - r-lib/sessioninfo
  - jimhester/covr
  - nhejazi/methyvimData

bioc_packages:
  - BiocStyle
  - BiocCheck
  - BiocParallel
  - BiocGenerics
  - S4Vectors
  - SummarizedExperiment
  - GenomeInfoDb
  - bumphunter
  - IRanges
  - limma
  - minfi
  - minfiData

after_success:
  ## coverage
  - travis_wait 80 Rscript -e "covr::codecov(line_exclusions = list('R/plots.R', 'R/utils.R'))"
  - R CMD BiocCheck .

on_failure:
  - "./travis-tool.sh dump_logs"

notifications:
  email:
    on_success: change
    on_failure: change

